import { useEffect, useState } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { publicUrl, supabase } from '../lib/supabase'

const tabs=['Dashboard','Projects','Project Media','Messages / Inbox','Skills','Journey / Experience','Certificates','Resume','Hero','About','Social Links','Site Settings']
const configs={
  Projects:{table:'projects',fields:['title','slug','summary','description','problem','built','project_type','role','year','tags','live_url','github_url','sort_order'],defaults:{title:'',slug:'',summary:'',description:'',problem:'',built:'',project_type:'Personal',role:'',year:2026,tags:'',live_url:'',github_url:'',sort_order:0,published:true,featured:false}},
  Skills:{table:'skills',fields:['category','name','sort_order'],defaults:{category:'Frontend',name:'',sort_order:0,published:true}},
  'Journey / Experience':{table:'journey',fields:['label','title','description','sort_order'],defaults:{label:'',title:'',description:'',sort_order:0,published:true}},
  Certificates:{table:'certificates',fields:['title','issuer','issue_date','sort_order'],defaults:{title:'',issuer:'',issue_date:'',sort_order:0,published:true}}
}
const contentMap={'Hero':'hero','About':'about','Social Links':'socials','Site Settings':'settings'}

export default function Admin(){
  const nav=useNavigate(); const [session,setSession]=useState(undefined),[authorized,setAuthorized]=useState(false),[tab,setTab]=useState('Dashboard'),[data,setData]=useState({projects:[],skills:[],journey:[],certificates:[],messages:[],resumes:[],content:[]}),[form,setForm]=useState({}),[editing,setEditing]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{if(!supabase){setSession(null);return} supabase.auth.getSession().then(async({data:d})=>{setSession(d.session);if(d.session){const {data:m}=await supabase.from('admin_users').select('user_id').eq('user_id',d.session.user.id).maybeSingle();setAuthorized(Boolean(m))}});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[])
  async function load(){const results=await Promise.all([supabase.from('projects').select('*,project_media(*)').order('sort_order'),supabase.from('skills').select('*').order('sort_order'),supabase.from('journey').select('*').order('sort_order'),supabase.from('certificates').select('*').order('sort_order'),supabase.from('contact_messages').select('*').order('created_at',{ascending:false}),supabase.from('resumes').select('*').order('created_at',{ascending:false}),supabase.from('site_content').select('*').order('key')]);setData({projects:results[0].data||[],skills:results[1].data||[],journey:results[2].data||[],certificates:results[3].data||[],messages:results[4].data||[],resumes:results[5].data||[],content:results[6].data||[]})}
  useEffect(()=>{if(authorized)load()},[authorized])
  const cfg=configs[tab], list=cfg?data[cfg.table]:[]
  function begin(item=null){setEditing(item);setForm(item?{...item,tags:Array.isArray(item.tags)?item.tags.join(', '):item.tags||''}:{...cfg.defaults})}
  async function save(e){e.preventDefault();setBusy(true);const payload={...form};['id','created_at','updated_at','project_media'].forEach(k=>delete payload[k]);if(tab==='Projects')payload.tags=String(payload.tags||'').split(',').map(x=>x.trim()).filter(Boolean);const q=editing?supabase.from(cfg.table).update(payload).eq('id',editing.id):supabase.from(cfg.table).insert(payload);const {error}=await q;setBusy(false);setNotice(error?.message||'Saved successfully.');if(!error){setEditing(null);setForm({...cfg.defaults});load()}}
  async function remove(item){if(!confirm(`Delete “${item.title||item.name}”?`))return;const {error}=await supabase.from(cfg.table).delete().eq('id',item.id);setNotice(error?.message||'Deleted.');load()}
  async function toggle(item,key){await supabase.from(cfg.table).update({[key]:!item[key]}).eq('id',item.id);load()}
  async function upload(file,folder){const ext=file.name.split('.').pop();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('portfolio-media').upload(path,file,{upsert:false});if(error)throw error;return path}
  async function uploadProject(e){e.preventDefault();const formEl=e.currentTarget,fd=new FormData(formEl),id=fd.get('project');setBusy(true);try{const cover=fd.get('cover');if(cover?.size){const path=await upload(cover,`projects/${id}/cover`);await supabase.from('projects').update({cover_path:path}).eq('id',id)}for(const file of fd.getAll('screens'))if(file?.size){const path=await upload(file,`projects/${id}/screenshots`);await supabase.from('project_media').insert({project_id:id,file_path:path,media_type:'image',alt_text:file.name})}const video=fd.get('video');if(video?.size){const path=await upload(video,`projects/${id}/videos`);await supabase.from('project_media').insert({project_id:id,file_path:path,media_type:'video',alt_text:video.name})}formEl.reset();setNotice('Project media uploaded.');load()}catch(err){setNotice(err.message)}setBusy(false)}
  async function uploadCertificate(e){e.preventDefault();const formEl=e.currentTarget,fd=new FormData(formEl),id=fd.get('certificate');setBusy(true);try{const payload={};for(const [name,folder] of [['pdf','certificates/pdfs'],['thumbnail','certificates/thumbnails']]){const file=fd.get(name);if(file?.size)payload[`${name}_path`]=await upload(file,folder)}await supabase.from('certificates').update(payload).eq('id',id);formEl.reset();setNotice('Certificate files uploaded.');load()}catch(err){setNotice(err.message)}setBusy(false)}
  async function uploadResume(e){e.preventDefault();const formEl=e.currentTarget,fd=new FormData(formEl),file=fd.get('file');setBusy(true);try{const path=await upload(file,'resume');await supabase.from('resumes').update({published:false}).eq('published',true);await supabase.from('resumes').insert({label:fd.get('label'),version:fd.get('version'),file_path:path,published:true});formEl.reset();setNotice('Current resume updated.');load()}catch(err){setNotice(err.message)}setBusy(false)}
  async function saveContent(e){e.preventDefault();const fd=new FormData(e.currentTarget),key=contentMap[tab];try{const value=JSON.parse(fd.get('value'));const {error}=await supabase.from('site_content').upsert({key,value});setNotice(error?.message||'Content saved.');load()}catch{setNotice('Value must be valid JSON.')}}
  if(session===undefined)return <main className="admin-loading">Loading secure dashboard…</main>;if(!session)return <Navigate to="/admin/login" replace/>;if(!authorized)return <main className="auth-page"><div className="auth-card"><h1>Access denied.</h1><p>Your account is not listed in admin_users.</p><button className="admin-primary" onClick={()=>supabase.auth.signOut().then(()=>nav('/admin/login'))}>Sign out</button></div></main>
  return <div className="dashboard"><aside><a className="brand" href="/">salman<span>.</span></a><p>PORTFOLIO CMS</p><nav>{tabs.map(x=><button className={tab===x?'active':''} key={x} onClick={()=>{setTab(x);setEditing(null);setNotice('')}}>{x}</button>)}</nav><button className="signout" onClick={()=>supabase.auth.signOut()}>Sign out</button></aside><main className="dash-main"><header><div><span>ADMIN DASHBOARD</span><h1>{tab}</h1></div>{cfg&&<button className="admin-primary" onClick={()=>begin()}>+ Add new</button>}</header>{notice&&<div className="notice" role="status">{notice}</div>}
    {tab==='Dashboard'&&<div className="admin-cards"><article><strong>{data.projects.length}</strong><p>Projects</p></article><article><strong>{data.messages.filter(x=>!x.is_read).length}</strong><p>New messages</p></article><article><strong>{data.certificates.length}</strong><p>Certificates</p></article></div>}
    {cfg&&<><section className="admin-list">{list.map(item=><article key={item.id}><div><h3>{item.title||item.name}</h3><small>{item.published?'Published':'Draft'}{item.featured?' · Featured':''}</small></div><div className="row-actions"><button onClick={()=>toggle(item,'published')}>{item.published?'Unpublish':'Publish'}</button>{tab==='Projects'&&<button onClick={()=>toggle(item,'featured')}>{item.featured?'Unfeature':'Feature'}</button>}<button onClick={()=>begin(item)}>Edit</button><button className="danger" onClick={()=>remove(item)}>Delete</button></div></article>)}</section><form className="editor" onSubmit={save}><h2>{editing?'Edit':'Add'} record</h2><div className="form-grid">{cfg.fields.map(name=><Field key={name} name={name} value={form[name]} set={setForm} textarea={['summary','description','problem','built'].includes(name)} wide={['summary','description','problem','built'].includes(name)} type={['year','sort_order'].includes(name)?'number':name==='issue_date'?'date':'text'}/>)}<label className="check"><input type="checkbox" checked={Boolean(form.published)} onChange={e=>setForm({...form,published:e.target.checked})}/> Published</label>{tab==='Projects'&&<label className="check"><input type="checkbox" checked={Boolean(form.featured)} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label>}</div><button className="admin-primary" disabled={busy}>{busy?'Saving…':'Save'}</button></form></>}
    {tab==='Project Media'&&<div className="media-layout"><form className="editor" onSubmit={uploadProject}><h2>Project media</h2><label>Project<select name="project" required>{data.projects.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><label>Cover image<input name="cover" type="file" accept="image/*"/></label><label>Screenshots<input name="screens" type="file" accept="image/*" multiple/></label><label>Demo video<input name="video" type="file" accept="video/*"/></label><button className="admin-primary" disabled={busy}>Upload media</button></form><form className="editor" onSubmit={uploadCertificate}><h2>Certificate files</h2><label>Certificate<select name="certificate" required>{data.certificates.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>PDF<input name="pdf" type="file" accept="application/pdf"/></label><label>Thumbnail<input name="thumbnail" type="file" accept="image/*"/></label><button className="admin-primary" disabled={busy}>Upload files</button></form><div className="media-gallery">{data.projects.flatMap(p=>(p.project_media||[]).map(m=><article key={m.id}>{m.media_type==='image'?<img src={publicUrl(m.file_path)} alt={m.alt_text||''}/>:<video src={publicUrl(m.file_path)} controls/>}<span>{p.title}</span></article>))}</div></div>}
    {tab==='Messages / Inbox'&&<section className="admin-list">{data.messages.map(m=><article key={m.id}><div><h3>{m.subject||'Portfolio enquiry'} — {m.name}</h3><small>{new Date(m.created_at).toLocaleString()} · {m.email}</small><p>{m.message}</p></div><div className="row-actions"><a href={`mailto:${m.email}?subject=Re: ${encodeURIComponent(m.subject||'Your portfolio message')}`}>Reply</a><button onClick={async()=>{await supabase.from('contact_messages').update({is_read:true}).eq('id',m.id);load()}}>Mark read</button><button className="danger" onClick={async()=>{if(confirm('Delete this message?')){await supabase.from('contact_messages').delete().eq('id',m.id);load()}}}>Delete</button></div></article>)}</section>}
    {tab==='Resume'&&<><form className="editor" onSubmit={uploadResume}><h2>Upload current resume</h2><label>Label<input name="label" defaultValue="MD Salman Resume" required/></label><label>Version / date<input name="version" placeholder="September 2026"/></label><label>PDF<input name="file" type="file" accept="application/pdf" required/></label><button className="admin-primary" disabled={busy}>Upload and publish</button></form>{data.resumes.map(r=><p key={r.id}><a href={publicUrl(r.file_path)} target="_blank" rel="noreferrer">{r.label} {r.version}</a> · {r.published?'Current':'Archived'}</p>)}</>}
    {contentMap[tab]&&<form className="editor" onSubmit={saveContent}><h2>Edit {tab}</h2><label>JSON value<textarea name="value" rows="14" defaultValue={JSON.stringify(data.content.find(x=>x.key===contentMap[tab])?.value||{},null,2)}/></label><button className="admin-primary">Save content</button></form>}
  </main></div>
}

function Field({name,value,set,textarea,wide,type='text'}){const props={name,value:value??'',onChange:e=>set(x=>({...x,[name]:type==='number'?Number(e.target.value):e.target.value}))};return <label className={wide?'wide':''}>{name.replaceAll('_',' ')}{textarea?<textarea rows="4" {...props}/>:<input type={type} {...props}/>}</label>}
